#ifndef MOBILE_GAME_TEMPLATE_DEFINES_H
#define MOBILE_GAME_TEMPLATE_DEFINES_H

#define APP_ORIENTATION_PORTRAIT 1
#define APP_ORIENTATION_LANDSCAPE 2

#ifndef APP_DISPLAY_NAME
#define APP_DISPLAY_NAME "Mobile Game Template"
#endif

#ifndef APP_ORIENTATION
#define APP_ORIENTATION APP_ORIENTATION_PORTRAIT
#endif

#if APP_ORIENTATION == APP_ORIENTATION_LANDSCAPE
#define APP_SCREEN_WIDTH 1280
#define APP_SCREEN_HEIGHT 720
#else
#define APP_SCREEN_WIDTH 720
#define APP_SCREEN_HEIGHT 1280
#endif

#endif
